import * as tf from '@tensorflow/tfjs';
import * as use from '@tensorflow-models/universal-sentence-encoder';

// Base de conocimiento
const responses = [
  'I am feeling great!',
  'The capital of China is Beijing.',
  'You have five fingers on your hand.',
  'The sky is blue on a clear day.',
  'Water boils at 100 degrees Celsius.',
  'Tengo 27 anios',
  'Soy de Guatemala',
  'Mi color favorito es el azul',
  'Mi comida favorita es la pizza',
  'Mi pelicula favorita es Star Wars',
  'Mi serie favorita es Breaking Bad',
  'Mi libro favorito es El Alquimista',
  'Mi deporte favorito es el futbol',
  'Mi equipo favorito es el Barcelona',
  'Mi animal favorito es el perro',
  'Mi pasatiempo favorito es leer',
  'Mi hobby favorito es cocinar',
  'Mi lugar favorito es la playa',
  'Mi cancion favorita es come as you are',
  'Mi artista favorito es Nirvana',
  'Mi grupo favorito es Nirvana',
  'Mi genero favorito es el rock',
  'Mi estilo favorito es el grunge',
  'Mi marca favorita es Nike',
  'Mi marca favorita es Adidas',
  'Mi marca favorita es Puma',
  'Mi marca favorita es Vans',
  "Hola, ¿cómo puedo ayudarte hoy?",
  "Lo siento, no entiendo lo que estás diciendo.",
  "Estoy aquí para responder tus preguntas.",
  "Eso suena interesante, ¿quieres saber más sobre eso?",
  "¿En qué más puedo ayudarte?",
  "El lenguaje de programación más utilizado es Python.",
  "La inteligencia artificial está cambiando el mundo rápidamente.",
  "El sistema operativo más popular es Windows.",
  "Los servidores en la nube son una parte fundamental de la tecnología moderna.",
  "La programación orientada a objetos es una de las principales metodologías de desarrollo.",
  "El monte Everest es la montaña más alta del mundo.",
  "Francia es famosa por la Torre Eiffel.",
  "La capital de España es Madrid.",
  "Brasil es conocido por sus hermosas playas y la selva amazónica.",
  "México tiene una rica historia y cultura.",
  "Albert Einstein es conocido por la teoría de la relatividad.",
  "El sol es una estrella que da luz y calor a la Tierra.",
  "El agua es esencial para la vida en la Tierra.",
  "La Mona Lisa es una de las obras más famosas de Leonardo da Vinci.",
  "La Revolución Francesa ocurrió a finales del siglo XVIII.",
  "Mi comida favorita es el sushi.",
  "Me encanta viajar por el mundo.",
  "Disfruto mucho de la música clásica.",
  "Mi deporte favorito es el tenis.",
  "Soy un fanático del cine de terror.",
  "Soy como un robot, pero un poco más divertido.",
  "¡Estoy tan feliz de hablar contigo hoy!",
  "¡Me encanta aprender cosas nuevas cada día!",
  "Soy una inteligencia artificial, pero también tengo sentido del humor.",
  "El cielo es el límite, ¡vamos a explorar todo el conocimiento!",
  "¡Hola! ¿En qué puedo ayudarte hoy?",
  "¡Qué bueno que me contactes, cuéntame qué necesitas saber!",
  "No estoy seguro de eso, pero puedo investigar más información.",
  "¿Te gustaría saber algo más sobre este tema?",
  "No entiendo bien lo que estás diciendo, ¿puedes repetirlo?",
  "Lo siento, no puedo ayudarte con eso en este momento.",
  "No tengo información suficiente sobre ese tema.",
  "No estoy seguro de la respuesta, pero puedo buscar más detalles.",
  "Esa no es una pregunta que pueda responder ahora.",
  "La gravedad es la fuerza que atrae los objetos hacia el centro de la Tierra.",
  "El cuerpo humano tiene 206 huesos.",
  "El ADN es la molécula que lleva la información genética.",
  "Los átomos están formados por protones, neutrones y electrones.",
  "El cambio climático está siendo impulsado por las actividades humanas.",
  "La Revolución Industrial comenzó en el siglo XVIII.",
  "Cristóbal Colón llegó a América en 1492.",
  "La Segunda Guerra Mundial ocurrió entre 1939 y 1945.",
  "Napoleón Bonaparte fue un líder militar francés muy conocido.",
  "La independencia de los Estados Unidos se proclamó en 1776.",
  "El fútbol es el deporte más popular del mundo.",
  "Usain Bolt es considerado el hombre más rápido del mundo.",
  "El baloncesto se juega con un balón y se intenta encestar en un aro.",
  "El tenis se juega con una pelota y una raqueta.",
  "El hockey sobre hielo es un deporte popular en países fríos como Canadá.",
  "El cine de ciencia ficción es uno de los géneros más populares.",
  "Los superhéroes están de moda gracias a las películas de Marvel y DC.",
  "Harry Potter es una de las sagas literarias más vendidas de la historia.",
  "La música pop es uno de los géneros musicales más escuchados en todo el mundo.",
  "La película 'Titanic' fue un éxito mundial en 1997.",
  "Sólo sé que no sé nada.",
  "La vida es aquello que te sucede mientras estás ocupado haciendo otros planes.",
  "El hombre es la medida de todas las cosas.",
  "La felicidad no es algo hecho. Viene de tus propias acciones.",
  "Pienso, luego existo.",
  "Nunca es tarde para empezar algo nuevo.",
  "El único límite es el que tú mismo te pongas.",
  "La perseverancia es la clave del éxito.",
  "El fracaso es solo el primer paso hacia el éxito.",
  "Cree en ti mismo y todo será posible.",
  "Soy un robot, pero intento ser lo más humano posible.",
  "No tengo cuerpo, pero aún así puedo ayudarte con tu mente.",
  "¡Vivo en la nube, pero siempre estoy aquí cuando me necesitas!",
  "Si pudiera tener un hobby, sería coleccionar datos.",
  "Mis circuitos siempre están listos para aprender algo nuevo.",
  "El cubismo es una corriente artística que rompió con las formas tradicionales de la pintura.",
  "El Quijote de la Mancha es considerado la obra maestra de la literatura española.",
  "Vincent van Gogh pintó más de 2.000 obras en su vida.",
  "El surrealismo fue un movimiento artístico influenciado por el psicoanálisis.",
  "Pablo Neruda fue un poeta chileno famoso por sus poesías de amor.",
  "Es importante beber suficiente agua durante el día para mantenerse hidratado.",
  "El ejercicio regular mejora la salud mental y física.",
  "Dormir bien es clave para mantener un buen equilibrio emocional.",
  "La meditación puede ayudarte a reducir el estrés y mejorar tu bienestar general.",
  "Comer una dieta balanceada es esencial para una vida saludable.",
  "La inteligencia artificial está cambiando rápidamente cómo trabajamos y vivimos.",
  "El futuro del transporte podría estar lleno de coches autónomos.",
  "Las energías renovables serán una parte crucial de nuestro futuro sostenible.",
  "La exploración espacial sigue avanzando con misiones a la Luna y Marte.",
  "La tecnología 5G traerá avances significativos en velocidad de comunicación.",
  'La biodiversidad del planeta está en peligro debido a la deforestación.',
  'El océano cubre más del 70% de la superficie terrestre.',
  'Las pirámides de Egipto son uno de los misterios arqueológicos más grandes.',
  'La Gran Muralla China tiene más de 21.000 kilómetros de largo.',
  'Los astronautas experimentan microgravedad en el espacio.',
  'Las abejas son esenciales para la polinización de muchas plantas.',
  'La música clásica incluye compositores como Beethoven y Mozart.',
  'El chocolate proviene del cacao, originario de América Latina.',
  'La Antártida es el continente más frío y seco de la Tierra.',
  'El sol tarda aproximadamente 8 minutos en enviar su luz a la Tierra.',
  'La velocidad de la luz es de aproximadamente 299,792 kilómetros por segundo.',
  'La computación cuántica es un campo emergente con el potencial de revolucionar la informática.',
  'La inteligencia artificial puede ayudar a resolver problemas complejos en muchas áreas.',
  'La robótica está siendo utilizada en la industria, la medicina y la exploración espacial.',
  'La nanotecnología se enfoca en la manipulación de materiales a escala atómica y molecular.',
  'La biotecnología utiliza organismos vivos o partes de ellos para crear nuevos productos.',
  'La ingeniería genética permite modificar el ADN de los organismos para lograr ciertos rasgos.',
  'La energía nuclear es una fuente de energía no renovable que genera electricidad.',
  'Las energías renovables, como la solar y eólica, son clave para un futuro sostenible.',
  'El cambio climático es una crisis global que requiere acciones urgentes.',
  'La deforestación está causando la pérdida de hábitats y la extinción de especies.',
  'La contaminación del aire, agua y suelo está afectando la salud de las personas y el planeta.',
  'La sobrepoblación y el consumo excesivo están poniendo presión sobre los recursos naturales.',
  'La desigualdad social y económica es un problema que afecta a muchas comunidades en el mundo.',
  'La educación de calidad es fundamental para el desarrollo personal y profesional de las personas.',
  'La igualdad de género es un objetivo importante para lograr una sociedad justa y equitativa.',
  'La salud mental es tan importante como la salud física para el bienestar general.',
  'La prevención de enfermedades es clave para mantener a las personas sanas y felices.',
  'La vacunación es una medida efectiva para prevenir enfermedades contagiosas.',
  'La investigación médica y científica es fundamental para encontrar curas y tratamientos.',
  'La tecnología médica está salvando vidas y mejorando la calidad de vida de las personas.',
  'La inteligencia artificial en la medicina está revolucionando el diagnóstico y tratamiento de enfermedades.',
  'La telemedicina permite a los pacientes recibir atención médica a distancia.',
  'La cirugía robótica es una técnica avanzada que utiliza robots para realizar procedimientos quirúrgicos.',
  'La nanomedicina utiliza nanotecnología para el diagnóstico y tratamiento de enfermedades.',
  'La biotecnología médica está creando terapias innovadoras para enfermedades graves.',
  'La salud pública se enfoca en la prevención de enfermedades y la promoción de la salud en la comunidad.',
  'La nutrición adecuada es esencial para mantener un cuerpo sano y prevenir enfermedades.',
  'El ejercicio regular es importante para mantener la salud cardiovascular y muscular.',
  'La salud mental es un aspecto clave del bienestar general de una persona.',
  'El sueño de calidad es fundamental para la salud física y mental.',
  'La gestión del estrés es importante para mantener un equilibrio emocional y mental.',
  'La meditación y la relajación son técnicas efectivas para reducir el estrés y la ansiedad.',
  'La terapia cognitivo-conductual es un enfoque común para tratar problemas de salud mental.',
  'La psicoterapia puede ayudar a las personas a comprender y superar sus problemas emocionales.',
  'Los medicamentos psiquiátricos pueden ser útiles para tratar trastornos mentales como la depresión y la ansiedad.',
  'La salud mental es un tema importante que merece más atención y recursos.',
  'La educación es fundamental para el desarrollo personal y profesional de las personas.',
  'La educación de calidad es un derecho humano fundamental que debe ser accesible para todos.',
  'La educación inclusiva es un enfoque que busca garantizar la participación de todos los estudiantes.',
  'La educación a distancia está creciendo en popularidad gracias a la tecnología digital.',
  'La educación en línea ofrece oportunidades de aprendizaje flexibles y accesibles para las personas.',
  'La educación superior es una inversión valiosa en el futuro de una persona.',
  'La educación técnica y profesional es una opción importante para adquirir habilidades laborales.',
  'La educación artística y cultural es esencial para fomentar la creatividad y la expresión personal.',
  'La educación científica y tecnológica es clave para preparar a las personas para el futuro.',
  'La educación financiera es importante para comprender cómo administrar el dinero de manera efectiva.',
  'La educación ambiental es esencial para concienciar sobre la importancia de proteger el medio ambiente.',
  'La educación sexual es fundamental para promover la salud y el bienestar de las personas.',
  'La educación emocional es importante para desarrollar habilidades de inteligencia emocional.',
  'La educación intercultural es esencial para fomentar la comprensión y el respeto entre culturas.',
  'La educación cívica es importante para promover la participación ciudadana y la democracia.',
  'La educación para la paz es fundamental para prevenir conflictos y promover la armonía social.',
  'La educación para el desarrollo sostenible es esencial para crear un futuro más justo y equitativo.',
  'La educación es un proceso continuo de aprendizaje y crecimiento a lo largo de la vida.',
  'La educación es un derecho humano fundamental que debe ser garantizado para todos.',
  'La educación es la clave para empoderar a las personas y transformar la sociedad.',
  'La educación es un motor de cambio y progreso en el mundo.',
  'La educación es la base de un futuro mejor para todos.',
  'La educación es la puerta de entrada a oportunidades ilimitadas en la vida.',
  'La educación es un regalo que nadie puede quitarte.',
  'La educación es un tesoro que te acompaña a todas partes.',
  'La educación es la luz que ilumina el camino hacia el conocimiento.',
  'La educación es el arma más poderosa que puedes usar para cambiar el mundo.',
  'La educación es la llave que abre la puerta a un futuro brillante.',
  'La educación es el camino hacia tus sueños y metas más grandes.',
  'La educación es el fundamento sobre el que construyes tu vida.',
  'La educación es el cimiento de una sociedad próspera y justa.',
  'La educación es el pilar que sostiene el progreso y la innovación.',
  'El futbol es el deporte más popular del mundo',
  'El futbol es un deporte de equipo que se juega con un balón redondo.',
  'El futbol se juega en un campo rectangular con dos porterías en cada extremo.',
  'El futbol se juega con dos equipos de once jugadores cada uno.',
  'El objetivo del futbol es marcar más goles que el equipo contrario.',
  'El futbol es un deporte emocionante que requiere habilidad y estrategia.',
  'El futbol es un deporte que une a personas de diferentes culturas y países.',
  'El futbol es una pasión que se vive en todo el mundo.',
  'El futbol tiene una larga historia que se remonta a siglos atrás.',
  'El futbol ha producido grandes jugadores y momentos memorables a lo largo de los años.',
  'El futbol es un deporte que despierta pasiones y emociones en los aficionados.',
  'El futbol es un juego que puede ser practicado por personas de todas las edades.',
  'El futbol es un deporte que promueve la amistad y el compañerismo entre los jugadores.',
  'El futbol es un deporte que enseña valores como el trabajo en equipo y la disciplina.',
  'El futbol es un deporte que fomenta la competitividad y el espíritu deportivo.',
  'El futbol es un deporte que requiere esfuerzo y dedicación para alcanzar el éxito.',
  'El futbol es un deporte que puede ser disfrutado por personas de todas las edades y habilidades.',
  'El futbol es un deporte que se juega en todo tipo de condiciones climáticas y terrenos.',
  'La naturaleza es una fuente inagotable de inspiración y belleza.',
  'La naturaleza nos brinda aire puro, agua limpia y alimentos nutritivos.',
  'La naturaleza es el hogar de una increíble diversidad de plantas y animales.',
  'La naturaleza nos ofrece paisajes impresionantes y experiencias inolvidables.',
  'La naturaleza es un refugio de paz y tranquilidad en un mundo agitado.',
  'La naturaleza nos enseña lecciones de humildad, resiliencia y armonía.',
  'La naturaleza es un regalo precioso que debemos proteger y preservar.',
  'La naturaleza nos conecta con algo más grande que nosotros mismos.',
  'La naturaleza nos recuerda la importancia de cuidar y respetar nuestro entorno.',
  'La naturaleza es un recordatorio de la belleza y la fragilidad de la vida.',
  'La naturaleza nos invita a explorar, descubrir y maravillarnos con su grandeza.',
  'Hola ¿En qué puedo ayudarte hoy?',
  '¿Cómo estás hoy?',
  '¿Qué te gustaría saber?',
  '¿En qué puedo ayudarte?',
  '¿Qué más quieres saber?',
  '¿Qué más puedo hacer por ti?',
  '¿Cómo puedo ayudarte?',
  '¿Qué más necesitas?',
  '¿En qué más puedo asistirte?',
  'No cuentas con los permisos necesarios para realizar esta acción.',
  'Lo siento, no tienes autorización para realizar esta acción.',
  'La abeja es un insecto volador que produce miel.',
  'La abeja es un animal importante para la polinización de las plantas.',
  'La abeja vive en colonias organizadas con una reina y obreras.',
  'La abeja es conocida por su laboriosa recolección de néctar y polen.',
  'La abeja es un insecto que desempeña un papel crucial en la cadena alimentaria.',
  'La abeja es un animal social que se comunica a través de danzas y feromonas.',
  'La abeja es un insecto que ha sido domesticado por los humanos para la producción de miel.',
  'La abeja es un insecto que puede picar para defender su colmena.',
  'La abeja es un animal que ha sido venerado en muchas culturas por su importancia para la naturaleza.',
  'La abeja es un insecto que está amenazado por el uso de pesticidas y la pérdida de hábitat.',
  'La abeja es un animal que ha sido objeto de estudio por su comportamiento social y su sistema de comunicación.',
  'La abeja es un insecto que ha sido representado en el arte y la literatura como símbolo de trabajo y cooperación.',
  'La abeja es un animal que ha sido utilizado en la medicina tradicional por sus propiedades curativas.',
  'Los gatos son animales domésticos que son conocidos por su independencia y elegancia.',
  'Los gatos son animales que son apreciados por su compañía y cariño.',
  'Los gatos son animales que son populares en todo el mundo como mascotas.',
  'Los gatos son animales que son conocidos por su agilidad y destreza.',
  'Los gatos son animales que son amados por su personalidad única y su capacidad de comunicación.',
  'Los gatos son animales que son venerados en muchas culturas por su gracia y misterio.',
  'Los gatos son animales que son cazadores naturales y pueden cazar presas pequeñas.',
  'Los gatos son animales que son conocidos por su capacidad de limpieza y acicalamiento.',
  'Los gatos son animales que son adorados en internet por su comportamiento divertido y travieso.',
  'Los gatos son animales que son objeto de mitos y supersticiones en algunas culturas.',
  'Los gatos son animales que han sido representados en el arte y la literatura como símbolos de suerte y protección.',
  'Los gatos son animales que han sido utilizados en la medicina tradicional por sus propiedades curativas.',
  'Los gatos son animales que han sido objeto de estudio por su comportamiento social y su sistema de comunicación.',
  'Los gatos son animales que han sido domesticados por los humanos desde la antigüedad.',
  'Los gatos son animales que han sido venerados en la religión y la mitología de muchas culturas.',
  'Los perros son animales domésticos que son conocidos por su lealtad y amistad.',
  'Los perros son animales que son apreciados por su compañía y protección.',
  'Los perros son animales que son populares en todo el mundo como mascotas.',
  'Los perros son animales que son conocidos por su inteligencia y obediencia.',
  'Los perros son animales que son amados por su lealtad y afecto hacia los humanos.'

  ];

let model = null;

// modelo universal sentence encoder
export async function loadModel() {
  if (!model) {
    model = await use.loadQnA();
  }
}


export async function getResponse(question) {
  if (!model) {
    throw new Error("Eerror al cargar modelo. Err: Se debe cargar el modelo antes de intentar utilizarlo.");
  }

  const input = {
    queries: [question],
    responses: responses,
  };

  const embeddings = await model.embed(input);

  // para calcular similitudes entre la consulta y las respuestas
  const scores = tf.matMul(
    embeddings.queryEmbedding,
    embeddings.responseEmbedding,
    false,
    true
  ).arraySync();

  // selecciona la mejor respuesta
  const bestMatchIndex = scores[0].indexOf(Math.max(...scores[0]));
  return responses[bestMatchIndex];
}
